version: '3'
services:
  db:
    image: postgres:13.2-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db/pg_data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_PASSWORD: 5315
      POSTGRES_DB: trixolma
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always

  api_service:
    container_name: api_service
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    links:
      - db
#    restart: always
    environment:
      - DEFAULT_EXECUTION_MODE=service

  api_auth:
    container_name: api_auth
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "9092:9092"
    links:
      - db
#    restart: always
    environment:
      - DEFAULT_EXECUTION_MODE=authorization

  site:
    container_name: site
    build:
      context: ./site
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"

  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    container_name: dashboard
    ports:
      - "3001:3001"
    links:
      - api_auth
      - api_service

  nginx:
    container_name: nginx
    build: ./nginx
    volumes:
      - ./nginx:/var/www/app/dashboard
#      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 443:443
    links:
      - api_auth
      - api_service
