version: '3'
services:
#  db:
#    image: postgres:latest
#    container_name: postgres
#    ports:
#      - "5432:5432"
#    volumes:
#      - ./db/pg_data:/var/lib/postgresql/data/pgdata
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: 5315
#      POSTGRES_DB: trixolma
#      PGDATA: /var/lib/postgresql/data/pgdata
#    restart: always

  db:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db/pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 5315
      POSTGRES_DB: trixolma
      PGDATA: /var/lib/postgresql/data
    restart: always

  api_service:
    container_name: api_service
    build:
      context: ./server
      dockerfile: ./docker/Dockerfile-service
    ports:
      - "9090:9090"
    links:
      - db
    restart: always
    environment:
      - DEFAULT_EXECUTION_MODE=service
      - DB_HOST=db
      - DB_NAME=trixolma
      - DB_USER=postgres
      - DB_PASSWORD=5315
      - TRIXOLMA_SID=tri_xolma_sid
      - TRIXOLMA_BASE_DOMAIN=.trixolma.localhost
      - COOKIE_MAX_AGE=null
      - SECRET=special_secret_field
      - STORAGE_SRC=http://localhost:9090

  api_auth:
    container_name: api_auth
    build:
      context: ./server
      dockerfile: ./docker/Dockerfile-auth
    ports:
      - "9092:9092"
    links:
      - db
    restart: always
    environment:
      - DEFAULT_EXECUTION_MODE=authorization
      - DB_HOST=db
      - DB_NAME=trixolma
      - DB_USER=postgres
      - DB_PASSWORD=5315
      - TRIXOLMA_SID=tri_xolma_sid
      - TRIXOLMA_BASE_DOMAIN=.trixolma.localhost
      - COOKIE_MAX_AGE=null
      - SECRET=special_secret_field
      - STORAGE_SRC=http://localhost:9090

#  migration:
#    image: sitetx_api_service
#    command: ["./wait-for-it/wait-for-it.sh", "api_service:9090", "--", "sequelize", "db:migrate"]
#    environment:
#      - DB_NAME=trixolma
#    links:
#      - api_service
#      - api_auth

#  site:
#    container_name: site
#    build:
#      context: ./site
#      dockerfile: ./Dockerfile
#    ports:
#      - "3000:3000"

#  dashboard:
#    build:
#      context: ./dashboard
#      dockerfile: Dockerfile
#    container_name: dashboard
#    ports:
#      - "3001:3001"
#    links:
#      - api_auth
#      - api_service

  nginx:
    container_name: nginx
    build: ./nginx
    volumes:
      - ./dashboard/build:/var/www/app/dashboard
      - ./site/build/:/var/www/app/site
    restart: always
    ports:
      - 80:80
      - 443:443
    links:
      - api_auth
      - api_service
