version: '3'
services:
  db:
    image: postgres:13.2-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_PASSWORD: 5315
      POSTGRES_DB: trixolma
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always

  api-service:
    build:
      context: "../serverNodeTX/"
      dockerfile: Dockerfile
    container_name: api-service
    ports:
      - "9090:9090"
#    links:
#      - db
#    restart: always
#    environment:
#      - DEFAULT_EXECUTION_MODE=service

  api-auth:
#    image: licege/trixolma-api-auth
    build:
      context: ../serverNodeTX/src/docker
      dockerfile: Dockerfile-auth
    container_name: api-auth
    ports:
      - "9092:9092"
    links:
      - db
#    restart: always
    environment:
      - DEFAULT_EXECUTION_MODE=authorization

#  site:
#    container_name: site
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "3000:3000"

  dashboard:
    image: licege/trixolma-dashboard
    container_name: dashboard
    ports:
      - "3001:3001"
    links:
      - api-auth
      - api-service
#  nginx:
#    image: nginx:1.19-alpine
#    container_name: nginx
#    volumes:
#      - ./default.conf:/etc/nginx/conf.d/default.conf
#    ports:
#      - 80:80
#      - 443:443
#    links:
#      - api-auth
#      - api-service
