version: '1'
services:
  db:
    image: postgres:13.2-alpine
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRESS_PASSWORD: 5315
      POSTGRESS_DB: trixolma
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
  api-service:
    image: node:16-alpine3.11
    container_name: api-service
    ports:
      - 9090:9090
    links:
      - db
  api-auth:
    image: node:16-alpine3.11
    container_name: api-auth
    ports:
      - 9092:9092
    links:
      - db
  nginx:
    image: nginx:1.19-alpine
    container_name: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 443:443
    links:
      - api-auth
      - api-service
